const ERROR_LIMIT = 5
const COL_TOOL_HEIGHT = 12
const COL_TOOL_CELL_HEIGHT = 12
const ROW_TOOL_WIDTH = 12
const CELL_MIN_WIDTH = 50
const PRIMARY_COLOR = '#35A7ED'

export {
  ERROR_LIMIT,
  COL_TOOL_HEIGHT,
  COL_TOOL_CELL_HEIGHT,
  ROW_TOOL_WIDTH,
  CELL_MIN_WIDTH,
  PRIMARY_COLOR,
}
